### ISSUE TITLE
Not working on windows 10

### ISSUE THREAD

**Issue by usttentire** [erdaltsksn/gh-label#1]
# Bug Report

## Current Behavior

**I'm getting an error:** This app can't run on your computer windows 10

## Expected Behavior

work flawless 😅

## Steps to reproduce the bug

1. I download it. ([windows_amd64 version](https://github.com/erdaltsksn/gh-label/releases/download/v0.1.0/gh-label_0.1.0_windows_amd64.tar.gz))
2. Click but not working. 

## Additional Context

- Windows 10 (64bit)

**Comment by erdaltsksn** [comment]
Could you try it with non-binary (go) version?

**STEPS:**

```sh
git clone https://github.com/erdaltsksn/gh-label.git
cd gh-label
go run main.go config --token ABCDACDSACAS
```

**NOTE:** Be sure you have at least go version 1.13 on your system.
